disable CGO and eliminate release build's use of upload-istioctl (#2666)
Automatic merge from submit-queue.

disable CGO and eliminate release build's use of upload-istioctl

The main point of this change was to eliminate the release build's use of the upload-istioctl script so that the build is now mostly just invoking targets against make (TBD if I'll later add an uber target so the build just needs to invoke make once ["make release-build"]).

I basically added a "istioctl-all" that will build istioctl-linux, istioctl-osx, istioctl-win.exe.

I tried to preserve the upload-istioctl's attempt to make non-static binaries, though I honestly don't know the motivation for this (assuming I'm interpreting "static" properly, which I take to mean a monolithic executable that doesn't attempt to pull in other libraries from the system).  In any case, "ldd" seems to think that go always creates a static binary on Linux (I didn't check Mac or Windows).

On my Linux dev system the cross-compile to Windows ran okay but Mac ran into problems (the docker image used for release builds doesn't hit this issue) :

\# net
/usr/lib/google-golang/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
\# os/user
/usr/lib/google-golang/src/os/user/getgrouplist_darwin.go: In function ‘mygetgrouplist’:
/usr/lib/google-golang/src/os/user/getgrouplist_darwin.go:14:11: warning: implicit declaration of function ‘getgrouplist’ [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^~~~~~~~~~~~

The problem goes away if I set CGO_ENABLED=0.  While investigating I noticed that the Makefile is missing a D suffix in "export CGO_ENABLE=0".  However, once I fixed this init.sh starting failing during "go get dep" from trying to install to system directories.  If I tried to workaround this using "-pkgdir <dir>" then a lot more files (mostly in the form of .a files) were getting added to the specified directory.  I first tried to workaround this by adding "CGO_ENABLED=1" to the "go get" for deps, but in total there's about 8 "go get" instance that I saw across the istio repo so rather than mess with these I just opted to delete the CGO_ENABLED line from Makefile and rely on gobuild.sh to set "CGO_ENABLED=0".  So far I've opted to leave the "CGO_ENABLED=1" on the "go get" for deps with the expectation this will help insulate the build from other parameters that might be set in the outside environment.

I simplified a few cases in the makefile from ${ISTIO_BIN}/$(@F) to just $@.  They're basically the same--the former was unnecessarily stripping off the directory path using $(@F) and appending the same directory back on again.